name: Create ASCII

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Welcome
              run: echo "Welcome to Github Actions"

            - name: Install Cowsay
              run: sudo apt-get install cowsay -y

            - name: Create a dragon
              run: cowsay -f dragon "Run for your life..I am gonna eat you" > dragon.txt

            - name: Check Dragon file
              run: grep -i dragon dragon.txt
                 
            - name: Show dragon
              run: cat dragon.txt
              
            - name: List Repositary
              run: ls -latr



