name: Create ASCII

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Welcome
              run: echo "Welcome to Github Actions"

            - name: Install Cowsay
              run: sudo apt-get install cowsay -y

            - name: Create a dog
              run: cowsay -f dragon "Bow ...bow...I am going to bite you" > dragon.txt

            - name: Check Dog file
              run: grep -i bow dragon.txt
              
            - name: List Repositary
              run: ls -latr



