name: My first workflow

on: push

jobs: 
    first_job:
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Welcome Message
        run: |
             echo "This is my first github action"
             ls -la
             cat README.md

      - name: Generate ASCII
        run: |
             sudo apt-get install cowsay -y 
             cowsay -f dog "Bow Bow ... I sense your presence" >> dog.txt
             cat dog.txt

      
