name: Generate ASCII

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install and create Cowsay
        run: |
          sudo apt-get install cowsay -y
          cowsay -f dragon "Run for your life..I am gonna eat you" > dragon.txt
    
      - name: Upload Dragon Text file
        uses: actions/upload-artifact@v4
        with:
        name: Dragon_file
        path: dragon.txt

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
      
    steps:
      - name: Test Cowsay
        uses: actions/download-artifact@v5
        with:
        name: Dragon_file
        run: grep -i life dragon.txt

  deploy_job:
    needs: [test_job]
    runs-on: ubuntu-latest
    uses: actions/download-artifact@v5
    with:
    name: Dragon_file
    steps:
      - name: Deploy Cowsay
        run: cat dragon.txt